name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:

  publish:

    name: Publish
    runs-on: ubuntu-latest


    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false

      - name: Set up Node.js
        uses: Systemcluster/actions@setup-node-v0
        id: setup-node
        with:
          cache: true
          package-manager: pnpm
          install: true

      - name: Test
        run: pnpm test

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{secrets.NPM_TOKEN}}
          tag: latest
          provenance: true

      - name: Create tag
        uses: actions/github-script@v7
        if: ${{ steps.publish.outputs.type }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.publish.outputs.version }}',
              sha: context.sha
            })
